version: "1.0"
info:
  model: int-scaffold
packages:
- name: Azsprotenant7moaaProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
services:
- serviceName: project.azsprotenant7moaa.integrations:edgeFlow_3
  packages:
  - name: Azsprotenant7moaaProject
    version: "1.0"
